cd /workspace/Progetto_Finale_Treni_AF-LF ;
npm i -g @angular/cli ;
cd client/ ;
npm i cors ;
npm i angular-google-charts ;
npm i ;
cd ../server ;
npm i cors ;
npm i mongodb ;
npm i express ;
npm i api-trenitalia ;
npm i ;
