cd /workspace/Progetto_Finale_Treni_AF-LF ;
npm i -g @angular/cli ;
cd client/ ;
npm i cors ;
npm install @agm/core --save ;
npm i @types/googlemaps@3.39.13 ;
npm i ;
cd ../server ;
npm i cors ;
npm i mongodb ;
npm i express ;
npm i redis ;
npm i api-trenitalia ;
npm i ;
