cd /workspace/Progetto_Finale_Treni_AF-LF ;
    echo -e "\n-----------------------------\n\nDisinstallazione Angular CLI ..." ;
    npm uninstall -g @angular/cli ;
    echo -e "\n-----------------------------\n\nDisinstallazione Nodemon ..." ;
    npm uninstall -g nodemon ;
cd client/ ;
    echo -e "\n-----------------------------\n\nDisinstallazione CORS ..." ;
    npm uninstall cors ;
    echo -e "\n-----------------------------\n\nDisinstallazione Leaflet ..." ;
    npm uninstall leaflet@1.7.1 ;
    npm uninstall @types/leaflet ;
    echo -e "\n-----------------------------\n\nDisinstallazione Dipendenze ..." ;
    npm uninstall ;
cd ../server ;
    echo -e "\n-----------------------------\n\nDisinstallazione GOT ..." ;
    npm uninstall got@11.0.2 ;
    echo -e "\n-----------------------------\n\nDisinstallazione JSDOM ..." ;
    npm uninstall jsdom@16.4.0 ;
    echo -e "\n-----------------------------\n\nDisinstallazione CORS ..." ;
    npm uninstall cors ;
    echo -e "\n-----------------------------\n\nDisinstallazione Request ..." ;
    npm uninstall request ;
    echo -e "\n-----------------------------\n\nDisinstallazione MongoDB ..." ;
    npm uninstall mongodb ;
    echo -e "\n-----------------------------\n\nDisinstallazione Express ..." ;
    npm uninstall express ;
    echo -e "\n-----------------------------\n\nDisinstallazione API TrenItalia ..." ;
    npm uninstall api-trenitalia ;
    echo -e "\n-----------------------------\n\nDisinstallazione Dipendenze ..." ;
    npm uninstall ;
echo -e "... Fine !"